### ISSUE TITLE
Metadeploy Preinstall Check for Chatter Enabled?

### ISSUE THREAD

**Issue by buzzbold** [SalesforceFoundation/OutboundFunds#57]
I just installed v 1.16 in a development org. Side note, I'm not trying to develop against Outbound Funds at the moment, so I did not opt to use a scratch org. Preinstall passed. Install failed. Error was:

`Could not process MDAPI response: Update of InstalledPackage outfunds: Error: (Disbursement__c-Disbursement Layout) The ActionId specified was invalid for ActionType QuickAction., Details: Disbursement__c-Disbursement Layout: The ActionId specified was invalid for ActionType QuickAction. (Funding_Program__c-Funding Program Layout) The ActionId specified was invalid for ActionType QuickAction., Details: Funding_Program__c-Funding Program Layout: The ActionId specified was invalid for ActionType QuickAction. (Funding_Request__c-Funding Request Layout) The ActionId specified was invalid for ActionType QuickAction., Details: Funding_Request__c-Funding Request Layout: The ActionId specified was invalid for ActionType QuickAction.
`
Results: https://install.salesforce.org/products/outbound-funds/1.16/install/jobs/2l7Dk8L

The installation was successful after enabling Chatter. I didn't isolate my test, but I also enabled _Add actions you create to the publisher on the home page, Chatter tab, and record detail pages._, and that may have been required as well.

I realize it's rare to see orgs without Chatter Enabled these days, but I'd like to suggest that that feature setting is included in Metadeploy pre-installation validation. Thanks, team!

**Comment by davidmreed** [comment]
This issue has been fixed and will be resolved in the next published version of Outbound Funds. Thank you!
