### ISSUE TITLE
GAU Expenditures component in the NPSP Extension does not honour GAU Expenditures and General Accounting Unit object permissions

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/OutboundFunds#79]
### Summary of the Issue

The Disbursement object contains a Lightning Component called Manage Expenditures. This component allows a user to view, edit and delete GAU Expenditures for a Disbursement.

Currently this component runs in system mode and so allows a user who does not have read/create/delete object permissions for GAU Expenditures to create, update or delete a record(s) i.e a user who has no access to GAU Expenditures can create, update or delete a GAU Expenditure record using the component.

Additionally, a user without Read access to General Accounting Units can view the name of GAU records via the component - either by viewing existing GAU Expenditure records surfaced by the component, or via the GAU lookup in the component itself.

### Steps to Replicate

- Create a test user and assign this user to a profile that has No Access to GAU Expenditures and No Access to General Accounting Units
- Login as the test user, view the GAU Expenditures tab of the Disbursement record with an existing GAU Expenditure record associated to the Disbursement
- Confirm the user can view the GAU Expenditure record and the name of the General Accounting Unit associated to the GAU Expenditure
- Confirm the user can lookup other GAU records via the GAU lookup in the component
- A user will be able to successfully edit or delete any existing GAU Expenditure records using the component. If they try to create a new GAU Expenditure via the component they will may also be able to create a record.

Note: I did receive an error at one stage during test creation of the GAU Expenditure record but I could not replicate the error in subsequent testing. If you receive an error trying to create a new GAU Expenditure, adding Read access to the General Accounting Unit for the user does seem to allow the user to create a new GAU Expenditure in all testing.

**Comment by jamesbsfdc** [comment]
W-8799914

**Comment by spelak-salesforce** [comment]
Fixed in [[W-8799914] GAU Expenditures component does not honour object/field-level permissions SalesforceFoundation/OutboundFundsNPSP#30](https://github.com/SalesforceFoundation/OutboundFundsNPSP/pull/30)
