### ISSUE TITLE
Automatically create GAU Expenditures through assignment on Funding Program

### ISSUE THREAD

**Issue by farahcharania** [SalesforceFoundation/OutboundFunds#87]
In NPSP, we can assign GAU Allocations on a Campaign which are then automatically added to opportunities associated with the campaign. Replicate this on the GAU Expenditures side by giving the ability to define GAU Expenditures on a Funding Program which are automatically created on the disbursements related to the funding program.

**Comment by kschaefges** [comment]
Hello! 

Thanks for your suggestion!  However, we don't provide support or log new feature requests here in github.  Please log your suggestion on the [Idea Exchange ](https://trailblazer.salesforce.com/ideaSearch?filter=Nonprofit+%3E+Outbound+Funds+Module).

Thanks!
Kim
